503 cda sim time sync
usdot-fhwa-OPS/V2X-Hub pull request #504
Opened 2023-03-29 20:37 UTC by paulbourelly999

# PR Details
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[V2XHUB Contributing Guide](https://github.com/usdot-fhwa-OPS/V2X-Hub/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-04-04 22:18 UTC, paulbourelly999 commented
@saina-ramyar Only added you as a secondary reviewer if you have time. Otherwise you can largely ignore this PR.

2023-04-06 21:08 UTC, davidgayman requested changes
Pual looks good. Only minor notes for you to follow up on.

2023-04-06 21:08 UTC, davidgayman commented on kowl/kowl.yaml
> +###################################################################
Unfamiliar with Kowl, but if the interface works that is sufficuent.

2023-04-06 21:08 UTC, davidgayman commented on src/v2i-hub/CDASimAdapter/src/CDASimAdapter.cpp
> +            std::string _simulation_ip = sim::get_sim_config(sim::SIMULATION_IP);
Confirmed you have documented them.

2023-04-06 21:14 UTC, paulbourelly999 commented on src/tmx/TmxUtils/src/PluginClientClockAware.cpp
>      void PluginClientClockAware::HandleTimeSyncMessage(tmx::messages::TimeSyncMessage &msg, routeable_message &routeableMsg ) {
See the V2X-Hub Plugin Programming guide. This is the required method signature for message handlers

2023-04-06 21:15 UTC, paulbourelly999 commented on src/tmx/TmxUtils/src/simulation/SimulationUtils.cpp
> +        if (std::getenv(SIMULATION_MODE)) {
Not sure what this comment is meant to say

2023-04-06 21:16 UTC, paulbourelly999 commented on src/tmx/TmxUtils/src/simulation/SimulationUtils.cpp
> +        if (std::getenv(SIMULATION_MODE)) {
Oh sure I can address this

2023-04-07 14:30 UTC, paulbourelly999 commented on src/v2i-hub/CDASimAdapter/src/CDASimAdapter.cpp
> +        this->BroadcastMessage<tmx::messages::TimeSyncMessage>(msg, _name, 0 , IvpMsgFlags_None);
Yes, other V2X-Hub plugins receive it through tmx to avoid making V2X-Hub unnecessarily depend on Kafka and CARMA Streets receives it via kafka.

2023-04-07 14:51 UTC, paulbourelly999 commented on src/v2i-hub/CDASimAdapter/src/CDASimAdapter.cpp
> +                time_producer->send(payload);
Not sure what you are referring to in this comment.

2023-04-07 18:16 UTC, merged