Update actions with start and stop locations at PVL lab
usdot-fhwa-OPS/V2X-Hub pull request #619
Opened 2024-06-27 14:03 UTC by dan-du-car

# PR Details
## Description
Update V2X Hub Port Drayage Plugin actions with new start/stop locations for testing in PVL Lab:
- PICKUP location: [3.7, -5.8]
- EXIT_STAGING_AREA location: [0.0, 0.2]

Latitude is mapped to Y axis, and longitude is mapped to X axis.
The location is picked from the pvl graph: https://github.com/usdot-fhwa-stol/c1t_bringup/blob/develop/graphs/pvl_graph.geojson?short_path=4609dc2

## Related Issue
NA

## Motivation and Context
NA

## How Has This Been Tested?
NA

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[V2XHUB Contributing Guide](https://github.com/usdot-fhwa-OPS/V2X-Hub/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-06-27 19:51 UTC, paulbourelly999 requested changes
Please add a related JIRA Ticket. Also It may be worth while creating a separate SQL file for the C1T testing. This file is currently used for our functionality testing. If we change things here that impact that we need to update that documentation

2024-07-01 13:46 UTC, paulbourelly999 requested changes
I know I was initially on the fence about this but could we add a README here outlining what this sql file is for and how to use it.
Example
### PVL Actions
These are Port Drayage actions created for the PVL Lab for testing of C1T functionality.
**Optional: Included some screen shot of the actions on a map**
### Instructions 
```docker-compose
db:
   image: mysql:8.0
   volumes:
       ./mysql/pvl_lab/port_drayage.sql


```

2024-07-01 13:58 UTC, dan-du-car commented
> Please add a related JIRA Ticket. Also It may be worth while creating a separate SQL file for the C1T testing. This file is currently used for our functionality testing. If we change things here that impact that we need to update that documentation

@paulbourelly999  Addressed

2024-07-01 14:25 UTC, paulbourelly999 commented on configuration/mysql/pvl_lab/README.md
> +## Instructions
@dan-du-car  lol these were place holder instructions. I think as the are currently written they do not work. You have to update the volume here and maybe add a sentence about replacing the old actions with the ones configured for PVL

2024-07-01 14:27 UTC, paulbourelly999 requested changes
My instructions were just place holders. They need a little editing to make them actually work.

2024-07-01 15:27 UTC, merged